// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA27LcASyJJzKIgbcIgi7VQEMSXoD6-QLs',
    appId: '1:914645404158:web:79e50b09233442aa46d8af',
    messagingSenderId: '914645404158',
    projectId: 'yo-bro-8f36e',
    authDomain: 'yo-bro-8f36e.firebaseapp.com',
    storageBucket: 'yo-bro-8f36e.firebasestorage.app',
    measurementId: 'G-ZB9S9XRH4T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVcRaCWviZx81OA9SuwvmSAbgENJ24_Wk',
    appId: '1:914645404158:ios:93d287f22983950346d8af',
    messagingSenderId: '914645404158',
    projectId: 'yo-bro-8f36e',
    storageBucket: 'yo-bro-8f36e.firebasestorage.app',
    iosBundleId: 'com.example.nvs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVcRaCWviZx81OA9SuwvmSAbgENJ24_Wk',
    appId: '1:914645404158:ios:4ced5c970103e66346d8af',
    messagingSenderId: '914645404158',
    projectId: 'yo-bro-8f36e',
    storageBucket: 'yo-bro-8f36e.firebasestorage.app',
    iosBundleId: 'com.example.yobro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA27LcASyJJzKIgbcIgi7VQEMSXoD6-QLs',
    appId: '1:914645404158:web:1242cf332067a4e546d8af',
    messagingSenderId: '914645404158',
    projectId: 'yo-bro-8f36e',
    authDomain: 'yo-bro-8f36e.firebaseapp.com',
    storageBucket: 'yo-bro-8f36e.firebasestorage.app',
    measurementId: 'G-SD6KZLPN7G',
  );
}
