// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eymrxnkitlfwzoadjikl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bXJ4bmtpdGxmd3pvYWRqaWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDc1NzksImV4cCI6MjA1OTcyMzU3OX0.CMWD14L5N0miC5NC9m97R4QP0TZvc_oh2PYe2yzExZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);